version: "3"

services:
  api:
    build: ./
    container_name: api
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      MONGODB_URL: mongodb://dev_db_admin_username:dev_db_admin_password@mongo:27017
      PORT: 5000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./src:/opt/app/src
      # - ./node_modules:/opt/app/node_modules # If this is needed, some more configuration is needed, contact docker author
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.2.3-bionic
    container_name: db
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_db_admin_username
      MONGO_INITDB_ROOT_PASSWORD: dev_db_admin_password

  mongo_admin_interface:
    image: mongo-express:0.54.0
    container_name: db_admin_page
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      # ME_CONFIG_MONGODB_SERVER: dev_db
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev_db_admin_username
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev_db_admin_password
    depends_on:
      - mongo

  redis:
    image: redis:5.0.7
    container_name: redis
    ports:
      - "6379:6379"
