export const fieldName: string = 'Field'
export const fieldTypeName: string = 'FieldType'
export const collectionItemName: string = 'CollectionItem'
export const collectionName: string = 'Collection'
export const collectionAccessName: string = 'CollectionAccess'
export const fieldTypeAccessName: string = 'FieldTypeAccess'
